export const tempMessages = [
  {
    attributes: {},
    body: {
      content: 'Hello ',
      lastModifyOperatorId: undefined,
      lastModifyTime: undefined,
      modifyCount: undefined,
      targetLanguageCodes: undefined,
      translations: [Object],
      type: 'txt',
    },
    chatType: 0,
    conversationId: '2',
    deliverOnlineOnly: false,
    direction: 'send',
    from: '2',
    groupAckCount: 0,
    hasDeliverAck: false,
    hasRead: true,
    hasReadAck: false,
    isBroadcast: false,
    isChatThread: false,
    isContentReplaced: false,
    isOnline: true,
    localMsgId: '1735640167000',
    localTime: 1735640167000,
    msgId: '1366123273393277898',
    needGroupAck: false,
    receiverList: [],
    serverTime: 1735640161056,
    status: 2,
    to: '2',
  },
];
